{"uuid": "de2f69dc-208f-432e-875e-bc7ecfec0680", "children": ["b73e6ec0-a838-43a8-8f22-497920dccaeb", "bfef1188-1190-4e08-bb7f-be2ef206317c", "d166ecf1-672b-4a7e-9a3b-29b441787415", "f26b0989-9df7-4205-9e15-a2968900901b", "564ad5aa-6c1b-420a-9de3-35d2ed1d7a8e", "a8b8ec54-daa8-4e23-be47-7dd2cb120a30", "10f69eaf-197a-4bff-912c-be0c3fc8d251", "c7ad129f-66da-47e3-b525-6962f7849e68", "7af253e0-0781-4c8a-a9f1-dce77de38647", "3282cf24-e0a7-4271-bd23-267a739aeb96", "1ef4c186-0946-455e-97bc-75cc3420b96f", "39ac5386-9b75-4e7e-8996-c66444f464f7", "332a311b-0868-4eb3-afab-bd28f0d44002", "b7538074-77d5-413b-a18d-aef8bcdbbd18", "78b050da-71aa-4e7b-87f1-e54bfd44eb1a", "12652035-83f0-4296-991d-99a89af90958", "33b8b2d2-4d10-4982-907d-5676c25a3401", "2bec3df6-c7d6-4896-8335-6ef5960a5d2f", "e07033af-7599-490a-ad0a-20569c944e1b", "41003d90-db8e-479a-8868-aceed31329b5", "248a39d2-29c4-4d5c-8c56-b29f93b378e8", "f0beca5b-62fc-4295-a6d0-9a67b1b567eb", "287add92-1947-4b1d-a1cf-626cdc06572a"], "befores": [{"name": "init_driver", "status": "passed", "start": 1678859973142, "stop": 1678859974493}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=38117): Max retries exceeded with url: /session/a8d7dfe3299777c42d54bdb51924aa7d/cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90c80343d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/home/sujith/codebase/BGE_Framework_Design/Test_Suites/conftest.py\", line 29, in init_driver\n    driver.delete_all_cookies()\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 730, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1678860031280, "stop": 1678860031285}], "start": 1678859973142, "stop": 1678860031285}