{"uuid": "13907f6b-3de5-4bac-b912-229d3037cee8", "children": ["b6986d4e-3c7c-401d-b4b0-ae4a399dbc26", "d15c65c9-f058-4a6b-ae4a-ec1f4e206f79", "aad443c6-a61a-4f63-a2f0-6b9b8fcb3af7", "b94303f5-f684-4162-887c-59a039ebb977", "9329de2f-f770-4246-be9c-794a53669e3a", "715ed996-baf6-402b-bb34-bd5f63b9db3e", "0a53814e-fee7-4e2e-bfd4-68cf4ce6d284", "4baf3ca6-8c03-4361-8570-1562b01b8aa0", "ac274d7b-7add-4fd9-a805-d481617df957", "6c27a720-3cfa-4e9b-83e9-3d3a05c62d0c", "092cc003-0d4d-4e95-a0ec-fc8681e92d0d", "31fe1386-88f1-465b-96b5-84dafe66ba25", "765918e2-96b5-413d-b8d5-89b8311e3b93", "d2b79f1a-eccd-4399-b226-9b7385a5c00b", "3974937a-a21c-41f8-9de3-93f61c0aee9b", "624bb639-6f66-444c-b8f5-a5662e898b10", "6e16b4f8-73a7-41f6-86ea-72efeeaf8d7c", "be461f9c-1e3c-4d55-8d72-da45068a85a5", "1066c9a2-9bd5-4852-87d6-21d86fbc85ee", "ac465942-b2ef-4207-80d7-a932dea3e6e1", "b5ec9067-0012-40d5-b455-2361d4a573d4", "ba93da53-4c6e-43e3-86b1-fc06a578d274", "e2f837ae-819a-4c31-8041-51eaa146ac9d", "b16cab25-d44e-4811-a964-4c98293b7160", "c70a17d7-d769-43fb-be7d-5b934dd7ffb2"], "befores": [{"name": "init_driver", "status": "passed", "start": 1678876938178, "stop": 1678876939341}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39405): Max retries exceeded with url: /session/2b21c0dec600c59416f00730a0050c39/cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcb15c2890>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/home/sujith/codebase/BGE_Framework_Design/Test_Suites/conftest.py\", line 29, in init_driver\n    driver.delete_all_cookies()\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 730, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1678877000396, "stop": 1678877000399}], "start": 1678876938178, "stop": 1678877000399}