{"uuid": "e4dec6fb-bde7-4422-881d-e86a0daa2a58", "children": ["df3230bd-0e1f-45f0-baa8-ac04a51f1f2a", "69e35d55-08cc-451d-b216-52f7c2223bf3", "8859b8fd-ccca-4cc5-8f33-beb57c9a949b", "5cdc1018-c368-4d9a-9d73-6e523597b6f2", "d888c5b8-c147-46e5-9663-f83aea3aabfc", "087d41be-bd4b-4c6d-8e40-281b344f837c", "c062e02b-c2fa-4d36-8549-4b1c555ec2eb", "e5d8d10a-29e2-444c-9289-1b2731978000", "ee4a1203-cef8-441e-9c6e-a049c80f82bb", "c619f08c-ff30-4a52-a29d-df74a79f1ac6", "08124838-3358-46f7-bf55-ba7e2359bb41", "a9a6a3ad-ea1d-413e-b07d-89b7dce21867", "7ca636ab-f892-45f4-a3be-75e73e73b368", "552e7827-61ae-4dd9-94e0-b08aa5170845", "9fc0039c-876c-4a26-bb96-ecefbbe9d5b2", "22580301-e505-4d05-9788-b50cb216b482", "210adfd8-6e18-43d1-89a5-39040b1765b8", "9e0b5623-8635-4faf-a24f-7ef8f3598324", "2dd88214-f644-4537-bc1d-58c6faeab5b8", "485bbfc9-6c3a-4ffa-a272-7ea45902b04b", "9d6364f6-50a4-48c8-974f-c212979f5694", "e5faf635-3b5c-45b1-ad00-1c90b874d948", "20772908-918b-4af2-804a-5af70e28b95d"], "befores": [{"name": "init_driver", "status": "passed", "start": 1678856892323, "stop": 1678856893487}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=48697): Max retries exceeded with url: /session/dfb02769ec447113cc53c7e524739f17/cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34407de080>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/home/sujith/codebase/BGE_Framework_Design/Test_Suites/conftest.py\", line 29, in init_driver\n    driver.delete_all_cookies()\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 730, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1678856964065, "stop": 1678856964068}], "start": 1678856892323, "stop": 1678856964068}