{"uuid": "69debcb4-2e99-48f4-b39f-0289334432ea", "children": ["30937d53-a574-4910-8aa7-7f5225d7cd82", "f5eafc55-3a0d-42e8-bc46-e6b7afd0260f", "6ce18e7f-b0c3-46bd-88cb-009b0254f9cf", "7a374d3d-a59b-4b86-83b9-c9b4043c8f7c", "7613ef08-b601-4179-82b9-ff023a22d4be", "1e5ad9c4-60e6-47fa-ae1d-e6a48252582f", "25d4344f-4f61-4605-a767-38ffc05eff83", "6597f7ee-646b-45a3-ab13-611ec8bf96eb", "afcdc556-f3c5-41e5-b8a5-6fea1ee964cc", "566208c3-039b-4b6a-8dbd-1ed1d22a6f90", "4944e30e-0b39-4690-b6f6-2f28e3a29d7e", "17b449ca-8992-4bb9-9aab-e7bdc0ac2126", "6f4599de-a391-44ca-a8c2-aae02f223354", "28295bcb-66c3-45c4-9517-1f8d447f32d1", "d22c0c85-a4ea-4177-bc4c-0f5d2817ccd7", "2a45937e-da85-42e2-b1ca-c8378ea4a584", "a59b1a05-1d58-4786-a57e-a95ae4652c81", "45e3dc3c-ea48-4ebb-8b84-9f89949126ac", "2542e316-3bce-4043-9e40-bb6b755d37cb", "0f917b90-0838-4011-9bdb-bbe8c78f96b5"], "befores": [{"name": "init_driver", "status": "passed", "start": 1678800791022, "stop": 1678800792607}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=45781): Max retries exceeded with url: /session/bec7e27e5ed3be10ee2cd442c0d51619/cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff70c460ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/home/sujith/codebase/BGE_Framework_Design/Test_Suites/conftest.py\", line 29, in init_driver\n    driver.delete_all_cookies()\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 730, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1678800833227, "stop": 1678800833229}], "start": 1678800791022, "stop": 1678800833229}