{"uuid": "ba3dae5a-cee2-4dec-b8b4-2a62f62af904", "children": ["5a92002b-a9d4-4269-bb15-7b65d2c0470f", "adb83de2-d4e8-4e59-9db3-a43b25af2d4f", "eaf8343f-c078-47b1-806a-41c3897647c5", "01b4fad3-0b71-4fa1-a9a3-d2a471f3864e", "f99358a4-0d61-431b-ad10-b0b28ab1a0b1", "176638a5-92bc-424e-9530-f6e1a7745edc", "6f8f5d85-c686-4822-81c5-8739ae402993", "e22e37d8-5809-43ec-8824-c86464a35f99", "218f42ba-bcb7-4c82-b09f-3021a9a088bd", "99744737-6bd7-420a-b231-fd55fb002ae8", "064039e9-7f53-4d22-b8a5-dce62ef4eec7", "d7550f94-5e6d-4580-b410-540fda45f7fa", "6b52cb77-62ab-4220-888d-5fc01bace898", "21c55c55-413d-4a73-9368-ce38f84eac49", "0cc7b5ef-c791-4b40-b1e0-06dd4aec1897", "ea2b2fd3-6229-4c59-8542-c8f23204af58", "b87e379b-b310-4a02-8000-e978e47d352c", "938016b5-3fa2-4bdc-a836-3c13f02a6569", "752e4e80-2888-4101-afb9-5703b8e2e3d3", "9deeba07-c077-4f34-8340-66b39ae3fbfe", "e5431643-729c-42f3-9841-d71aca521c49", "4ec0a181-9701-45a9-a966-76b015119569", "9fc5f208-d591-43cd-baa0-4f8196283079", "dd043cb9-f1a6-42e4-81d0-503eda07b72e", "8b0f4c8f-4049-4074-8757-e253a1af9bac"], "befores": [{"name": "init_driver", "status": "passed", "start": 1678860342512, "stop": 1678860343676}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52209): Max retries exceeded with url: /session/a6255ca67db0f0bec52d204731bc3931/cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f67ef54ec80>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/home/sujith/codebase/BGE_Framework_Design/Test_Suites/conftest.py\", line 29, in init_driver\n    driver.delete_all_cookies()\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 730, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1678860405950, "stop": 1678860405953}], "start": 1678860342512, "stop": 1678860405953}